### PR TITLE
Remove obsolete call of searchInterface from interfaceToName

### LINKED ISSUE #32: interfaceToName breaks list of marker-interfaces in Plone
Disclaimer: I'm not really sure about this.

In https://github.com/plone/Products.CMFPlone/issues/2083 a issue with the zmi-view `/manage_interfaces` (code in `Products.Five.utilities.marker`) is discussed. The ZMI-View in question uses `zope.component.interface.interfaceToName` to display lists of available and provided marker-interfaces.

`interfaceToName` uses `searchInterfaceUtilities` to get them which in turn uses `isOrExtends()` instead of `extends()` since it was changed in https://github.com/zopefoundation/zope.component/commit/2e39b26054c8c1da36886b7ba8ba0d346d62d2d7#diff-65de6b69a0342d33e93d0098ac38b46cL220 by @tseaver.

Now `interfaceToName` has the line `assert len(ids) == 1, "Ambiguous interface names: %s"'%s.%s' % ids` to make sure only one interface is found. But `isOrExtends` implies that it can return more than one item. Either there is logic-error or the method is not used correctly in Zope. 

The line calling `searchInterfaceUtilities` has a comment:

    # XXX this search is pointless:  we are always going to return the
    #     same value whether or not we find anything.

We could:

1. Follow the commet, drop the search and change `interfaceToName` to simply return `'%s.%s' % (interface.__module__, interface.__name__)`. I tried this and it did not break any tests in zope.component.

2. If the method is indeed correct and the use in Products.Five is wrong we could instead change `Products.Five.utilities.marker._getInterfaceNames` to simply `return ['%s.%s' % (i.__module__, i.__name__) for i in interfaces]`. 

3. Anything else?

### PR DESCRIPTION
**Pull request by pbauer**
Fixes #32

### CODE REVIEW

**Comment by tseaver** [comment]
I have no problem with the substance of this change, but there should be a test failure:  coveralls reports we are at 100% before this PR, which doesn't remove any tests but *does* remove lines that were presumably covered.

@jamadden You're the one responsible for switching from `tox -e coverage` to coveralls to measure coverage:  can you explain?

**Comment by pbauer** [comment]
In https://github.com/zopefoundation/zope.browserpage/commit/b82f337a42192fef54caf9672329214a05e86931 I use exactly the same pattern as the original issue in Plone: A browsermenu is registered with id and interface:

```xml
<browser:menu
  id="test_menu"
  title="Test menu"
  interface="zope.browserpage.tests.test_page.ITestMenu"/>
```

When using `interfaceToName` on that interface an Error is rsaised: https://travis-ci.org/zopefoundation/zope.browserpage/builds/271922007

**Comment by mgedmin** [comment]
Speaking of coverage, well, we don't have branch coverage enabled, do we?  And it's not surprising that an assert statement that gets executed with the condition evaluating to False is marked as covered.

**Comment by jamadden** [comment]
Right, branch coverage is not enabled, so we just had to take both the `if` branch (which a search for one registration would do) and the alternative (which a search for nothing registered would do). Given that both alternatives  produce the same thing (`interface.__module__ + '.' + interface.__name__`), they cannot be distinguished from tests. The test case that was missing was one that *intentionally* set things up to fail (searching for multiple registrations).

**Comment by pbauer** [comment]
@jamadden are you saying that the pattern I use above (setting up a browsermenu with id and interface) is wrong? It has been used in zope.browsermenu, I only added the failing test.

**Comment by jamadden** [comment]
@pbauer I wasn't commenting on zope.browserpage, only on the tests in this package.

**Comment by tseaver** [comment]
@mgedmin There is an actual (non-assert) branch in the removed code.  How are the current tests exercising the [early return](https://github.com/zopefoundation/zope.component/pull/33/files#diff-65de6b69a0342d33e93d0098ac38b46cL125)?  Any why don't they fail in this PR?

**Comment by jamadden** [comment]
The [current tests](https://github.com/zopefoundation/zope.component/blob/master/src/zope/component/tests/test_interface.py#L355) exercise exactly the two cases that the code handled: one registered interface and no registered interfaces. They don't test the failure case of multiple registered interfaces (why not? Probably because that was *clearly* not supposed to happen, given the presence of an `assert`). Note that the two cases result in the same text being returned, which is the text that's still being returned.

**Comment by pbauer** [comment]
Can this be merged or is something still missing? If so, what exactly?

**Pull request merged**
