### PR TITLE
Add failing functional/integration tests for the interaction between zope.security/zope.proxy/zope.component

### PR DESCRIPTION
**Pull request by jamadden**
These previously existed in a zcml.rst doctest only and will fail under PyPy until zopefoundation/zope.security#11 and/or zopefoundation/zope.proxy#8 is fixed.

### CODE REVIEW

**Comment by tseaver** [comment]
@jamadden Still failing on PyPy3 after todays releases of zope.proxy and zope.security:

 https://travis-ci.org/zopefoundation/zope.component/jobs/64425022

**Comment by jamadden** [comment]
Hmm, it's not PyPy3 specific, it also fails if I set PURE_PYTHON under CPython 2.7-3.4. Something is wrong with proxies around iterators.

**Comment by jamadden** [comment]
Unfortunately this was a bug in zope.security and so PyPy3 will need zopefoundation/zope.security#13.

I apologize for not catching this before.

**Comment by jamadden** [comment]
Whoops, accidentally closed when the other related bug was merged.

**Comment by tseaver** [comment]
zope.security 4.0.3 has the iterator fix:  https://pypi.python.org/pypi/zope.security/4.0.3

I restarted the Travis build for the PR.

**Comment by jamadden** [comment]
And it's green! Yippee!

**Comment by tseaver** [comment]
Thank you for the test, and for the work to track down why it was failing!

**Pull request merged**
